# サイト情報
site_name: TechCommitチュートリアル
site_description: 'TechCommitを活用するためのチュートリアルサイト'
site_author: 'TechTraining'

# リポジトリ
repo_name: 'tech-training/tech-commit-tutorial'

# コピーライト
copyright: '&copy; 2020 株式会社テクトレ'

# デザイン設定
theme:
  name: 'material'
  language: 'ja'
  favicon: 'images/favicon.ico'
  palette:
    primary: 'indigo'
    accent: 'amber'
